from __future__ import annotations

from io import BytesIO
from datetime import datetime
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, HTMLResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen.canvas import Canvas

from app.metrics import metrics
from app.schemas import (
    MealPlanRequestSchema,
    MealPlanResponseSchema,
    MetricsDashboardSchema,
    RecipeMemorySchema,
    ShoppingListPdfRequestSchema,
    WorkflowStateSchema,
)
from app.state import state_store
from app.use_cases.meal_plan_use_case import MealPlanUseCase

app = FastAPI(
    title="Meal Prep Agent",
    description="Generate a five-day meal plan and shopping list from dietary preferences.",
    version="0.1.0",
)

planner = MealPlanUseCase()

STATIC_DIR = Path(__file__).resolve().parent / "static"
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


@app.post("/meal-plan", response_model=MealPlanResponseSchema)
def create_meal_plan(request: MealPlanRequestSchema) -> MealPlanResponseSchema:
    try:
        result = planner.create_plan(request)
        return MealPlanResponseSchema(
            raw_meal_plan=result.raw_meal_plan,
            raw_shopping_list=result.raw_shopping_list,
            nutrition_validation=result.nutrition_summary,
            budget_validation=result.budget_summary,
            daily_plan=list(result.daily_plan),
            shopping_items=list(result.shopping_items),
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@app.get("/")
def get_ui() -> FileResponse:
    return FileResponse(STATIC_DIR / "index.html")


@app.post("/shopping-list/pdf")
def generate_shopping_list_pdf(request: ShoppingListPdfRequestSchema):
    buffer = BytesIO()
    canvas = Canvas(buffer, pagesize=letter)
    width, height = letter
    margin = 50
    y = height - margin

    canvas.setFont('Helvetica-Bold', 18)
    canvas.drawString(margin, y, request.title)
    y -= 28
    canvas.setFont('Helvetica', 10)
    canvas.drawString(
        margin,
        y,
        f'Generated by Meal Prep Agent on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}',
    )
    y -= 28
    canvas.setFont('Helvetica', 12)

    for line in request.shopping_list.splitlines():
        line = line.strip()
        if not line:
            continue
        if y < margin + 30:
            canvas.showPage()
            y = height - margin
            canvas.setFont('Helvetica', 12)
        canvas.drawString(margin, y, line)
        y -= 18

    canvas.showPage()
    canvas.save()
    buffer.seek(0)
    return StreamingResponse(
        buffer,
        media_type='application/pdf',
        headers={'Content-Disposition': 'attachment; filename="shopping_list.pdf"'},
    )


@app.get("/metrics", response_model=MetricsDashboardSchema)
def get_metrics() -> MetricsDashboardSchema:
    dashboard_data = metrics.dashboard()
    return MetricsDashboardSchema(**dashboard_data)


@app.get("/recipe-memory", response_model=list[RecipeMemorySchema])
def get_recipe_memory() -> list[RecipeMemorySchema]:
    memories = state_store.get_recent_recipe_memories()
    return [RecipeMemorySchema(**memory.__dict__) for memory in memories]


@app.get("/workflow-state/{request_id}", response_model=WorkflowStateSchema)
def get_workflow_state(request_id: str) -> WorkflowStateSchema:
    state = state_store.get_state(request_id)
    if state is None:
        raise HTTPException(status_code=404, detail=f"Workflow state not found for request_id {request_id}")
    return WorkflowStateSchema(**state.to_dict())


@app.get("/metrics/html", response_class=HTMLResponse)
def get_metrics_html() -> str:
    return """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Meal Prep Agent - Metrics Dashboard</title>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.js"></script>
        <style>
            * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                padding: 20px;
            }
            .container {
                max-width: 1400px;
                margin: 0 auto;
            }
            header {
                color: white;
                margin-bottom: 30px;
            }
            h1 {
                font-size: 2.5em;
                margin-bottom: 10px;
            }
            .refresh-info {
                font-size: 0.9em;
                opacity: 0.9;
            }
            .grid-2 {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                gap: 20px;
                margin-bottom: 30px;
            }
            .grid-3 {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
                gap: 20px;
                margin-bottom: 30px;
            }
            .card {
                background: white;
                border-radius: 12px;
                padding: 20px;
                box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
                transition: transform 0.2s;
            }
            .card:hover {
                transform: translateY(-4px);
                box-shadow: 0 12px 24px rgba(0, 0, 0, 0.15);
            }
            .metric-card {
                text-align: center;
            }
            .metric-value {
                font-size: 2em;
                font-weight: bold;
                color: #667eea;
                margin: 10px 0;
            }
            .metric-label {
                color: #888;
                font-size: 0.9em;
                text-transform: uppercase;
                letter-spacing: 0.05em;
            }
            .chart-container {
                position: relative;
                height: 300px;
                margin-bottom: 10px;
            }
            .recent-requests-table {
                width: 100%;
                border-collapse: collapse;
                font-size: 0.9em;
            }
            .recent-requests-table th {
                background: #f5f5f5;
                padding: 12px;
                text-align: left;
                font-weight: 600;
                color: #333;
                border-bottom: 2px solid #ddd;
            }
            .recent-requests-table td {
                padding: 10px 12px;
                border-bottom: 1px solid #eee;
            }
            .recent-requests-table tr:hover {
                background: #f9f9f9;
            }
            .request-id-cell {
                font-family: 'Courier New', monospace;
                font-size: 0.85em;
                color: #667eea;
            }
            .section-title {
                font-size: 1.5em;
                font-weight: 600;
                margin: 30px 0 20px 0;
                color: white;
            }
            .agent-list {
                list-style: none;
            }
            .agent-item {
                padding: 15px;
                background: #f9f9f9;
                border-left: 4px solid #667eea;
                margin-bottom: 10px;
                border-radius: 4px;
            }
            .agent-name {
                font-weight: 600;
                color: #333;
                margin-bottom: 8px;
            }
            .agent-stats {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
                gap: 10px;
                font-size: 0.9em;
            }
            .agent-stat {
                color: #666;
            }
            .agent-stat-value {
                color: #667eea;
                font-weight: 600;
            }
            .empty-state {
                text-align: center;
                color: #999;
                padding: 30px;
                font-style: italic;
            }
            .refresh-btn {
                background: white;
                color: #667eea;
                border: none;
                padding: 10px 20px;
                border-radius: 6px;
                font-weight: 600;
                cursor: pointer;
                transition: all 0.2s;
            }
            .refresh-btn:hover {
                background: #f0f0f0;
            }
            .loading {
                opacity: 0.6;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <header>
                <h1>📊 Meal Prep Agent Metrics</h1>
                <div class="refresh-info">
                    <span id="last-updated">Loading...</span>
                    <button class="refresh-btn" onclick="refreshMetrics()">↻ Refresh Now</button>
                </div>
            </header>

            <div class="grid-2">
                <div class="card metric-card">
                    <div class="metric-label">Total Requests</div>
                    <div class="metric-value" id="total-requests">0</div>
                </div>
                <div class="card metric-card">
                    <div class="metric-label">Total Agent Calls</div>
                    <div class="metric-value" id="total-calls">0</div>
                </div>
                <div class="card metric-card">
                    <div class="metric-label">Total Tokens</div>
                    <div class="metric-value" id="total-tokens">0</div>
                </div>
                <div class="card metric-card">
                    <div class="metric-label">Total Cost</div>
                    <div class="metric-value" id="total-cost">$0.00</div>
                </div>
                <div class="card metric-card">
                    <div class="metric-label">Avg Latency</div>
                    <div class="metric-value" id="avg-latency">0ms</div>
                </div>
                <div class="card metric-card">
                    <div class="metric-label">Avg Cost/Request</div>
                    <div class="metric-value" id="avg-cost">$0.00</div>
                </div>
            </div>

            <div class="grid-3">
                <div class="card">
                    <h3 style="margin-bottom: 15px;">Token Distribution</h3>
                    <div class="chart-container">
                        <canvas id="tokenChart"></canvas>
                    </div>
                </div>
                <div class="card">
                    <h3 style="margin-bottom: 15px;">Agent Calls</h3>
                    <div class="chart-container">
                        <canvas id="agentCallsChart"></canvas>
                    </div>
                </div>
                <div class="card">
                    <h3 style="margin-bottom: 15px;">Agent Costs</h3>
                    <div class="chart-container">
                        <canvas id="agentCostsChart"></canvas>
                    </div>
                </div>
            </div>

            <div class="card">
                <h3 style="margin-bottom: 15px;">Agent Breakdown</h3>
                <ul class="agent-list" id="agent-breakdown">
                    <li class="empty-state">No agents have run yet</li>
                </ul>
            </div>

            <div class="card" style="margin-top: 20px;">
                <h3 style="margin-bottom: 15px;">Recent Requests</h3>
                <div style="overflow-x: auto;">
                    <table class="recent-requests-table" id="recent-requests-table">
                        <thead>
                            <tr>
                                <th>Request ID</th>
                                <th>Model</th>
                                <th>Created</th>
                                <th>Latency (ms)</th>
                                <th>Tokens</th>
                                <th>Cost</th>
                                <th>Agents</th>
                                <th>Operations</th>
                            </tr>
                        </thead>
                        <tbody id="recent-requests-body">
                            <tr><td colspan="8" class="empty-state">No requests yet</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <script>
            let tokenChart = null;
            let agentCallsChart = null;
            let agentCostsChart = null;

            async function refreshMetrics() {
                try {
                    document.body.classList.add('loading');
                    const response = await fetch('/metrics');
                    const data = await response.json();
                    updateDashboard(data);
                } catch (error) {
                    console.error('Failed to fetch metrics:', error);
                } finally {
                    document.body.classList.remove('loading');
                }
            }

            function updateDashboard(data) {
                // Update metric cards
                document.getElementById('total-requests').textContent = data.total_requests;
                document.getElementById('total-calls').textContent = data.total_agent_calls;
                document.getElementById('total-tokens').textContent = (
                    data.total_prompt_tokens + data.total_output_tokens
                ).toLocaleString();
                document.getElementById('total-cost').textContent = '$' + data.total_cost_usd.toFixed(4);
                document.getElementById('avg-latency').textContent = data.average_latency_ms.toFixed(1) + 'ms';
                document.getElementById('avg-cost').textContent = '$' + data.average_cost_per_request_usd.toFixed(6);
                document.getElementById('last-updated').textContent = 'Last updated: ' + new Date().toLocaleTimeString();

                // Update charts
                updateTokenChart(data);
                updateAgentCallsChart(data);
                updateAgentCostsChart(data);

                // Update agent breakdown
                updateAgentBreakdown(data);

                // Update recent requests
                updateRecentRequests(data);
            }

            function updateTokenChart(data) {
                const ctx = document.getElementById('tokenChart').getContext('2d');
                if (tokenChart) tokenChart.destroy();
                tokenChart = new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: ['Prompt Tokens', 'Output Tokens'],
                        datasets: [{
                            data: [data.total_prompt_tokens, data.total_output_tokens],
                            backgroundColor: ['#667eea', '#764ba2'],
                            borderColor: white,
                            borderWidth: 2
                        }]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: { legend: { position: 'bottom' } }
                    }
                });
            }

            function updateAgentCallsChart(data) {
                const ctx = document.getElementById('agentCallsChart').getContext('2d');
                if (agentCallsChart) agentCallsChart.destroy();
                
                const agents = Object.keys(data.agent_breakdown);
                const calls = agents.map(a => data.agent_breakdown[a].calls);
                
                agentCallsChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: agents,
                        datasets: [{
                            label: 'Calls',
                            data: calls,
                            backgroundColor: '#667eea',
                            borderRadius: 4
                        }]
                    },
                    options: {
                        indexAxis: 'y',
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: { legend: { display: false } },
                        scales: { x: { beginAtZero: true } }
                    }
                });
            }

            function updateAgentCostsChart(data) {
                const ctx = document.getElementById('agentCostsChart').getContext('2d');
                if (agentCostsChart) agentCostsChart.destroy();
                
                const agents = Object.keys(data.agent_breakdown);
                const costs = agents.map(a => data.agent_breakdown[a].total_cost_usd);
                
                agentCostsChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: agents,
                        datasets: [{
                            label: 'Cost ($)',
                            data: costs,
                            backgroundColor: '#764ba2',
                            borderRadius: 4
                        }]
                    },
                    options: {
                        indexAxis: 'y',
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: { legend: { display: false } },
                        scales: { x: { beginAtZero: true } }
                    }
                });
            }

            function updateAgentBreakdown(data) {
                const container = document.getElementById('agent-breakdown');
                const agents = Object.keys(data.agent_breakdown);
                
                if (agents.length === 0) {
                    container.innerHTML = '<li class="empty-state">No agents have run yet</li>';
                    return;
                }

                container.innerHTML = agents.map(agent => {
                    const stats = data.agent_breakdown[agent];
                    return `
                        <li class="agent-item">
                            <div class="agent-name">${agent}</div>
                            <div class="agent-stats">
                                <div class="agent-stat">
                                    Calls: <span class="agent-stat-value">${stats.calls}</span>
                                </div>
                                <div class="agent-stat">
                                    Avg Latency: <span class="agent-stat-value">${stats.average_latency_ms.toFixed(1)}ms</span>
                                </div>
                                <div class="agent-stat">
                                    Tokens: <span class="agent-stat-value">${(stats.total_prompt_tokens + stats.total_output_tokens).toLocaleString()}</span>
                                </div>
                                <div class="agent-stat">
                                    Cost: <span class="agent-stat-value">$${stats.total_cost_usd.toFixed(6)}</span>
                                </div>
                            </div>
                        </li>
                    `;
                }).join('');
            }

            function updateRecentRequests(data) {
                const tbody = document.getElementById('recent-requests-body');
                
                if (data.recent_requests.length === 0) {
                    tbody.innerHTML = '<tr><td colspan="8" class="empty-state">No requests yet</td></tr>';
                    return;
                }

                tbody.innerHTML = data.recent_requests.map(req => `
                    <tr>
                        <td class="request-id-cell">${req.request_id.substring(0, 8)}</td>
                        <td>${req.model_name}</td>
                        <td>${new Date(req.created_at).toLocaleTimeString()}</td>
                        <td>${req.latency_ms.toFixed(1)}</td>
                        <td>${(req.prompt_tokens + req.output_tokens).toLocaleString()}</td>
                        <td>$${req.cost_usd.toFixed(6)}</td>
                        <td>${req.agent_calls}</td>
                        <td>${req.operation_names.join(', ')}</td>
                    </tr>
                `).join('');
            }

            // Auto-refresh every 5 seconds
            setInterval(refreshMetrics, 5000);

            // Initial load
            refreshMetrics();
        </script>
    </body>
    </html>
    """
